// Package snapshot wraps git to provide a per-turn history of the agent's
// data directory. After each successful chat turn the agent commits any
// changes; recovery is `git reset --hard HEAD~N` from inside the data dir.
//
// Snapshots are best-effort. If git is missing or the repo is corrupted,
// snapshot calls log a warning and return nil — they must never block the
// chat reply.
package snapshot

import (
	"bytes"
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

const (
	authorName  = "Polaris Agent"
	authorEmail = "agent@polaris.local"
)

// gitignoreContent is auto-written on init. .archive/ is intentionally
// NOT ignored — the safety net itself should be recoverable.
const gitignoreContent = `# Auto-generated by Polaris Agent.
# Edit at your own risk; the agent may overwrite this on init.
.bash-audit.log
.uv-cache/
.venv/
secrets/
*.tmp
*.swp
`

// Snapshotter takes per-turn git commits inside dataDir.
//
// A nil receiver is valid and turns every method into a no-op — that's the
// disabled mode (GIT_ENABLED=false or git binary missing).
type Snapshotter struct {
	dataDir string
	mu      sync.Mutex
}

// New returns a Snapshotter, or nil if snapshots are disabled or git isn't
// usable. It performs lazy init: if dataDir/.git doesn't exist, runs
// `git init`, writes .gitignore, and creates the initial commit.
//
// Errors during init are logged but not fatal — we'd rather run the agent
// without snapshots than refuse to start.
func New(dataDir string, enabled bool) *Snapshotter {
	if !enabled {
		return nil
	}
	if _, err := exec.LookPath("git"); err != nil {
		log.Printf("snapshot: git binary not found, snapshots disabled (%v)", err)
		return nil
	}
	s := &Snapshotter{dataDir: dataDir}
	if err := s.ensureRepo(); err != nil {
		log.Printf("snapshot: init failed, snapshots disabled: %v", err)
		return nil
	}
	if err := s.commitStrayChanges(); err != nil {
		// Non-fatal; we'll commit them on the next normal turn.
		log.Printf("snapshot: could not commit stray changes: %v", err)
	}
	return s
}

// Commit stages everything in the data dir and commits it with a message
// containing the session ID and a UTC timestamp. Empty commits are
// skipped. Safe to call from concurrent goroutines.
//
// On a nil receiver this is a no-op. Errors are logged and returned but
// callers should generally not propagate them — a snapshot failure must
// never break a chat reply.
func (s *Snapshotter) Commit(sessionID string) error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	dirty, err := s.hasChanges()
	if err != nil {
		log.Printf("snapshot: status failed: %v", err)
		return err
	}
	if !dirty {
		return nil
	}
	if err := s.run("add", "-A"); err != nil {
		log.Printf("snapshot: add failed: %v", err)
		return err
	}
	stamp := time.Now().UTC().Format(time.RFC3339)
	msg := fmt.Sprintf("turn at %s", stamp)
	if sessionID != "" {
		msg = fmt.Sprintf("session=%s · %s", sanitizeSession(sessionID), stamp)
	}
	if err := s.run("commit", "-m", msg); err != nil {
		log.Printf("snapshot: commit failed: %v", err)
		return err
	}
	return nil
}

// Enabled reports whether the snapshotter is active. Useful for diagnostics.
func (s *Snapshotter) Enabled() bool { return s != nil }

func (s *Snapshotter) ensureRepo() error {
	if err := os.MkdirAll(s.dataDir, 0o755); err != nil {
		return err
	}
	gitDir := filepath.Join(s.dataDir, ".git")
	if _, err := os.Stat(gitDir); err == nil {
		// Repo exists — make sure .gitignore is current.
		return s.writeGitignoreIfMissing()
	}
	if err := s.run("init", "-q", "-b", "main"); err != nil {
		return fmt.Errorf("git init: %w", err)
	}
	if err := s.run("config", "user.name", authorName); err != nil {
		return err
	}
	if err := s.run("config", "user.email", authorEmail); err != nil {
		return err
	}
	if err := s.writeGitignoreIfMissing(); err != nil {
		return err
	}
	if err := s.run("add", "-A"); err != nil {
		return err
	}
	// Allow empty so the first commit always succeeds even on a fresh
	// data dir with no files yet.
	if err := s.run("commit", "--allow-empty", "-m", "initial"); err != nil {
		return fmt.Errorf("initial commit: %w", err)
	}
	log.Printf("snapshot: initialized repo at %s", gitDir)
	return nil
}

func (s *Snapshotter) writeGitignoreIfMissing() error {
	p := filepath.Join(s.dataDir, ".gitignore")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return os.WriteFile(p, []byte(gitignoreContent), 0o644)
}

// commitStrayChanges captures any uncommitted state from a previous run
// (likely a crash mid-turn) before we accept new turns.
func (s *Snapshotter) commitStrayChanges() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	dirty, err := s.hasChanges()
	if err != nil || !dirty {
		return err
	}
	if err := s.run("add", "-A"); err != nil {
		return err
	}
	stamp := time.Now().UTC().Format(time.RFC3339)
	return s.run("commit", "-m", "stray changes recovered at "+stamp)
}

func (s *Snapshotter) hasChanges() (bool, error) {
	out, err := s.output("status", "--porcelain")
	if err != nil {
		return false, err
	}
	return strings.TrimSpace(out) != "", nil
}

func (s *Snapshotter) run(args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = s.dataDir
	cmd.Env = gitEnv()
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

func (s *Snapshotter) output(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = s.dataDir
	cmd.Env = gitEnv()
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			return "", fmt.Errorf("git %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(string(ee.Stderr)))
		}
		return "", err
	}
	return string(out), nil
}

// gitEnv keeps git from picking up a developer's global config inside the
// container (or on a contributor's laptop) and from prompting for
// credentials.
func gitEnv() []string {
	return append(os.Environ(),
		"GIT_AUTHOR_NAME="+authorName,
		"GIT_AUTHOR_EMAIL="+authorEmail,
		"GIT_COMMITTER_NAME="+authorName,
		"GIT_COMMITTER_EMAIL="+authorEmail,
		"GIT_TERMINAL_PROMPT=0",
	)
}

// sanitizeSession strips characters that would confuse a single-line
// commit message (newlines, tabs, control chars).
func sanitizeSession(id string) string {
	var b strings.Builder
	for _, r := range id {
		if r < 32 || r == 127 {
			continue
		}
		b.WriteRune(r)
	}
	out := b.String()
	if len(out) > 64 {
		out = out[:64]
	}
	return out
}
